services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ecommerce_pg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  coupon-thrift-service:
    build:
      context: .
      dockerfile: ./coupon-thrift-service/Dockerfile
    ports:
      - "9090:9090"
    networks:
      - ecommerce-network
    depends_on:
      - mysql

  ecommerce:
    build:
      context: .     # change to all root path
      dockerfile: ./ecommerce/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

      - PG_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ecommerce_pg
      - PG_DATASOURCE_USERNAME=postgres
      - PG_DATASOURCE_PASSWORD=password

      - THRIFT_HOST=coupon-thrift-service
      - THRIFT_PORT=9090

      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - postgres
      - coupon-thrift-service

volumes:
  mysql_data:
  postgres_data:

networks:
  ecommerce-network:
